### ISSUE TITLE
Please is PSTCKRSA missing in the static framework release?

### ISSUE THREAD

**Issue by tolu360** [ibrahimlawal/paystack-ios-1#1]
Hello Ibrahim,

I didn't want to leave this on the official home for the repo because it's more of a clarification than an issue. I was trying to add iOS support to cordova-plugin-paystack using the static `Paystack.framework` but I keep running into the errors each time I attempt to build the app:

`Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_PSTCKRSA", referenced from:
      objc-class-ref in Paystack(PSTCKCardParams.o)
ld: symbol(s) not found for architecture i386
`

Please could it be possible that the interface and implementation for `PSTCKRSA` were not bundled with the module in the static framework release at all? Thanks

**Comment by ibrahimlawal** [comment]
Thanks @tolu360 , I'll check the code and try rebuild. How did you integrate? pods, carthage or ...

**Comment by tolu360** [comment]
I downloaded the standalone release at https://github.com/PaystackHQ/paystack-ios/releases/

**Comment by tolu360** [comment]
Hi @ibrahimlawal, any luck with the rebuild and were you able to reproduce my issue?

**Comment by ibrahimlawal** [comment]
Yes, pls try this.
[framework.zip](https://github.com/ibrahimlawal/paystack-ios/files/187277/framework.zip)

**Comment by tolu360** [comment]
Thanks, but my build is still returning the same errors with the new bundle here.

**Comment by ibrahimlawal** [comment]
Thanks for your patience Tolu, pls try this. I checked to make sure the PSTCKRSA.h is listed in public headers.
[PaystackiOS.zip](https://github.com/ibrahimlawal/paystack-ios/files/188597/PaystackiOS.zip)

**Comment by tolu360** [comment]
Thank you Ibrahim, the bundled framework is good now - the build error is gone!

**Comment by ibrahimlawal** [comment]
Awesome. Thanks for finding and helping squash this issue!
